import { useCallback, useEffect, useMemo, useState } from "react";
import { Gamepad2, RotateCcw, Trophy } from "lucide-react";

type GameId = "snake" | "pong" | "breakout" | "invaders" | "flip";
const scoreKey = "lucu-arcade.scores.v1";

const games: { id: GameId; title: string; subtitle: string; color: string }[] = [
  { id: "snake", title: "Snake Neon", subtitle: "Guie a cobra, recolha luzes.", color: "lime" },
  { id: "pong", title: "Pong Relay", subtitle: "Defenda a sua linha de energia.", color: "cyan" },
  { id: "breakout", title: "Brick Pulse", subtitle: "Quebre a grelha de memória.", color: "amber" },
  { id: "invaders", title: "Orbit Invaders", subtitle: "Limpe o sector com disparos precisos.", color: "violet" },
  { id: "flip", title: "Memory Flip", subtitle: "Encontre os pares da colecção.", color: "rose" },
];

function readScores() { try { return JSON.parse(localStorage.getItem(scoreKey) || "{}") as Partial<Record<GameId, number>>; } catch { return {}; } }
function saveScore(id: GameId, score: number) { const scores = readScores(); if (score > (scores[id] || 0)) localStorage.setItem(scoreKey, JSON.stringify({ ...scores, [id]: score })); }

function GameHeader({ title, score, onReset, children }: { title: string; score: number; onReset: () => void; children: React.ReactNode }) {
  return <><div className="game-topline"><div><span className="eyebrow">ARCADE / EM JOGO</span><h3>{title}</h3></div><div className="game-score"><Trophy size={15} /> {score} <button aria-label="Reiniciar jogo" onClick={onReset}><RotateCcw size={16} /></button></div></div>{children}</>;
}

function SnakeGame() {
  const [snake, setSnake] = useState<number[]>([65, 64, 63]); const [food, setFood] = useState(41); const [direction, setDirection] = useState(1); const [running, setRunning] = useState(false); const [score, setScore] = useState(0); const [over, setOver] = useState(false);
  const reset = () => { setSnake([65, 64, 63]); setFood(41); setDirection(1); setScore(0); setOver(false); setRunning(true); };
  const chooseDirection = (next: number) => { if (next !== -direction) { setDirection(next); setRunning(true); } };
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "ArrowUp") chooseDirection(-12); if (event.key === "ArrowDown") chooseDirection(12); if (event.key === "ArrowLeft") chooseDirection(-1); if (event.key === "ArrowRight") chooseDirection(1); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  useEffect(() => { if (!running || over) return; const timer = window.setInterval(() => setSnake((current) => { const head = current[0]; const row = Math.floor(head / 12); const next = head + direction; const crossed = (direction === 1 && next % 12 === 0) || (direction === -1 && next % 12 === 11) || next < 0 || next > 143 || (direction === -12 && row === 0) || (direction === 12 && row === 11); if (crossed || current.includes(next)) { setOver(true); setRunning(false); saveScore("snake", score); return current; } if (next === food) { setScore((value) => value + 10); let newFood = (food + 37) % 144; while (current.includes(newFood)) newFood = (newFood + 17) % 144; setFood(newFood); return [next, ...current]; } return [next, ...current.slice(0, -1)]; }), 165); return () => window.clearInterval(timer); }, [running, over, direction, food, score]);
  return <GameHeader title="Snake Neon" score={score} onReset={reset}><p className="game-help">Setas ou controlos abaixo. Recolha os pontos de luz sem tocar nas paredes.</p><div className="snake-grid">{Array.from({ length: 144 }, (_, cell) => <span key={cell} className={snake.includes(cell) ? "snake-cell" : cell === food ? "snake-food" : ""} />)}</div><div className="dpad"><button onClick={() => chooseDirection(-12)}>↑</button><div><button onClick={() => chooseDirection(-1)}>←</button><button onClick={() => chooseDirection(12)}>↓</button><button onClick={() => chooseDirection(1)}>→</button></div></div>{over && <p className="game-status">Fim de jogo. A sua melhor pontuação foi guardada localmente.</p>}</GameHeader>;
}

function PongGame() {
  const [paddle, setPaddle] = useState(2); const [ball, setBall] = useState({ x: 5, y: 2, dx: 1, dy: 1 }); const [score, setScore] = useState(0); const [missed, setMissed] = useState(false);
  const reset = () => { setPaddle(2); setBall({ x: 5, y: 2, dx: 1, dy: 1 }); setScore(0); setMissed(false); };
  useEffect(() => { if (missed) return; const timer = window.setInterval(() => setBall((value) => { let { x, y, dx, dy } = value; let nextX = x + dx; let nextY = y + dy; if (nextY < 0 || nextY > 5) { dy *= -1; nextY = y + dy; } if (nextX === 10) { if (Math.abs(nextY - paddle) <= 1) { setScore((current) => current + 5); dx = -1; nextX = x + dx; } else { setMissed(true); saveScore("pong", score); return value; } } if (nextX < 0) { dx = 1; nextX = 1; } return { x: nextX, y: nextY, dx, dy }; }), 280); return () => window.clearInterval(timer); }, [paddle, missed, score]);
  return <GameHeader title="Pong Relay" score={score} onReset={reset}><p className="game-help">Mova a raquete da direita antes da esfera chegar. Use os botões ou ↑ ↓.</p><div className="pong-field">{Array.from({ length: 66 }, (_, i) => { const x = i % 11; const y = Math.floor(i / 11); return <span key={i} className={`${x === 0 && Math.abs(y - ball.y) <= 1 ? "cpu-paddle" : ""} ${x === 10 && Math.abs(y - paddle) <= 1 ? "player-paddle" : ""} ${x === ball.x && y === ball.y ? "pong-ball" : ""}`} />; })}</div><div className="game-controls"><button onClick={() => setPaddle((value) => Math.max(1, value - 1))}>↑ Subir</button><button onClick={() => setPaddle((value) => Math.min(4, value + 1))}>↓ Descer</button></div>{missed && <p className="game-status">Perdeu a transmissão. Reinicie para uma nova ronda.</p>}</GameHeader>;
}

function BreakoutGame() {
  const initialBricks = useMemo(() => Array.from({ length: 24 }, (_, i) => i), []); const [bricks, setBricks] = useState(initialBricks); const [paddle, setPaddle] = useState(3); const [ball, setBall] = useState({ x: 3, y: 5, dx: 1, dy: -1 }); const [score, setScore] = useState(0); const [over, setOver] = useState(false);
  const reset = () => { setBricks(initialBricks); setPaddle(3); setBall({ x: 3, y: 5, dx: 1, dy: -1 }); setScore(0); setOver(false); };
  useEffect(() => { if (over || !bricks.length) return; const timer = window.setInterval(() => setBall((state) => { let { x, y, dx, dy } = state; let nx = x + dx; let ny = y + dy; if (nx < 0 || nx > 7) { dx *= -1; nx = x + dx; } if (ny < 0) { dy = 1; ny = 1; } const brickIndex = nx + ny * 8; if (bricks.includes(brickIndex)) { setBricks((items) => items.filter((item) => item !== brickIndex)); setScore((value) => value + 10); dy *= -1; ny = y + dy; } if (ny === 6) { if (Math.abs(nx - paddle) <= 1) { dy = -1; ny = 5; } else { setOver(true); saveScore("breakout", score); return state; } } return { x: nx, y: ny, dx, dy }; }), 260); return () => window.clearInterval(timer); }, [bricks, over, paddle, score]);
  return <GameHeader title="Brick Pulse" score={score} onReset={reset}><p className="game-help">Use ← → para manter o pulso em jogo. Limpe todos os blocos.</p><div className="breakout-field"><div className="brick-grid">{Array.from({ length: 24 }, (_, i) => <span key={i} className={bricks.includes(i) ? "brick-on" : "brick-off"} />)}</div><div className="breakout-lane">{Array.from({ length: 64 }, (_, i) => { const x = i % 8; const y = Math.floor(i / 8); return <span key={i} className={`${x === ball.x && y === ball.y ? "break-ball" : ""} ${y === 7 && Math.abs(x - paddle) <= 1 ? "break-paddle" : ""}`} />; })}</div></div><div className="game-controls"><button onClick={() => setPaddle((value) => Math.max(1, value - 1))}>← Esquerda</button><button onClick={() => setPaddle((value) => Math.min(6, value + 1))}>Direita →</button></div>{!bricks.length && <p className="game-status">Grelha limpa. Excelente ronda.</p>}{over && <p className="game-status">A esfera saiu do campo. Reinicie para tentar outra vez.</p>}</GameHeader>;
}

function InvadersGame() {
  const [ship, setShip] = useState(3); const [enemies, setEnemies] = useState<number[]>([1, 3, 5, 0, 2, 4]); const [shot, setShot] = useState<number | null>(null); const [score, setScore] = useState(0); const [over, setOver] = useState(false);
  const reset = () => { setShip(3); setEnemies([1, 3, 5, 0, 2, 4]); setShot(null); setScore(0); setOver(false); };
  const fire = () => { if (over || shot !== null) return; setShot(ship); window.setTimeout(() => { setEnemies((current) => { if (current.includes(ship)) { setScore((value) => value + 15); return current.filter((enemy) => enemy !== ship); } return current; }); setShot(null); }, 260); };
  useEffect(() => { if (over || !enemies.length) return; const timer = window.setInterval(() => { setEnemies((current) => { const shifted = current.map((enemy) => (enemy + 1) % 7); if (shifted.includes(ship)) { setOver(true); saveScore("invaders", score); } return shifted; }); }, 1200); return () => window.clearInterval(timer); }, [over, enemies.length, ship, score]);
  return <GameHeader title="Orbit Invaders" score={score} onReset={reset}><p className="game-help">Desloque a nave e dispare para a sua coluna. Não deixe os invasores chegar.</p><div className="invader-field"><div className="invader-row">{Array.from({ length: 7 }, (_, col) => <span key={`a${col}`} className={enemies.slice(0, 3).includes(col) ? "invader" : ""}>⌁</span>)}</div><div className="invader-row">{Array.from({ length: 7 }, (_, col) => <span key={`b${col}`} className={enemies.slice(3).includes(col) ? "invader" : ""}>⌁</span>)}</div><div className="laser-row">{Array.from({ length: 7 }, (_, col) => <span key={col} className={shot === col ? "laser" : ""} />)}</div><div className="ship-row">{Array.from({ length: 7 }, (_, col) => <span key={col} className={ship === col ? "ship" : ""}>▲</span>)}</div></div><div className="game-controls"><button onClick={() => setShip((value) => Math.max(0, value - 1))}>← Mover</button><button className="fire-button" onClick={fire}>Disparar</button><button onClick={() => setShip((value) => Math.min(6, value + 1))}>Mover →</button></div>{!enemies.length && <p className="game-status">Sector limpo. Vitória.</p>}{over && <p className="game-status">Um invasor alcançou a sua posição.</p>}</GameHeader>;
}

const cards = ["♫", "♫", "◒", "◒", "✦", "✦", "▣", "▣", "☾", "☾", "●", "●"];
function FlipGame() {
  const [deck, setDeck] = useState<string[]>(() => [...cards].sort(() => Math.random() - 0.5)); const [opened, setOpened] = useState<number[]>([]); const [matched, setMatched] = useState<number[]>([]); const [moves, setMoves] = useState(0);
  const reset = () => { setDeck([...cards].sort(() => Math.random() - 0.5)); setOpened([]); setMatched([]); setMoves(0); };
  const flip = (index: number) => { if (opened.length === 2 || opened.includes(index) || matched.includes(index)) return; const next = [...opened, index]; setOpened(next); if (next.length === 2) { setMoves((value) => value + 1); window.setTimeout(() => { if (deck[next[0]] === deck[next[1]]) { setMatched((current) => [...current, ...next]); saveScore("flip", Math.max(0, 100 - moves * 5)); } setOpened([]); }, 520); } };
  const score = Math.max(0, 100 - moves * 5); return <GameHeader title="Memory Flip" score={score} onReset={reset}><p className="game-help">Abra dois símbolos, encontre os pares e use menos movimentos.</p><div className="flip-grid">{deck.map((card, index) => <button key={`${card}-${index}`} className={opened.includes(index) || matched.includes(index) ? "flipped" : ""} onClick={() => flip(index)}>{opened.includes(index) || matched.includes(index) ? card : "?"}</button>)}</div>{matched.length === deck.length && <p className="game-status">Colecção completa em {moves} movimentos.</p>}</GameHeader>;
}

export function ArcadeRetro() {
  const [active, setActive] = useState<GameId>("snake"); const [scores, setScores] = useState(readScores()); const game = games.find((item) => item.id === active)!;
  useEffect(() => { const timer = window.setInterval(() => setScores(readScores()), 700); return () => window.clearInterval(timer); }, []);
  return <section className="space-shell arcade-shell" id="arcade"><div className="section-heading"><div><span className="eyebrow">03 / ARCADE RETRO</span><h2>Pequenas pausas, jogos reais.</h2><p>Cinco jogos retro feitos para jogar no browser. As pontuações ficam apenas neste dispositivo.</p></div><span className="local-chip"><Gamepad2 size={15} /> Sem conta, sem anúncios</span></div><div className="arcade-reference" aria-hidden="true" style={{ backgroundImage: "url('/manus-storage/lucu-arcade-retro-reference_3fe39348.png')" }} /><div className="arcade-layout"><div className="arcade-select">{games.map((item) => <button key={item.id} onClick={() => setActive(item.id)} className={`${item.id === active ? "selected" : ""} arcade-${item.color}`}><span className="machine-screen">{item.id === "snake" ? "S" : item.id === "pong" ? "P" : item.id === "breakout" ? "B" : item.id === "invaders" ? "I" : "M"}</span><span><strong>{item.title}</strong><small>{item.subtitle}</small></span><em><Trophy size={12} /> {scores[item.id] || 0}</em></button>)}</div><div className="game-cabinet" data-game={game.color}>{active === "snake" && <SnakeGame />}{active === "pong" && <PongGame />}{active === "breakout" && <BreakoutGame />}{active === "invaders" && <InvadersGame />}{active === "flip" && <FlipGame />}</div></div></section>;
}
