import { relations } from "drizzle-orm";
import { boolean, integer, pgEnum, pgTable, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("user_role", ["user", "admin"]);
export const computerStatusEnum = pgEnum("computer_status", ["available", "occupied", "maintenance"]);
export const reservationStatusEnum = pgEnum("reservation_status", ["pending", "confirmed", "cancelled", "completed"]);

export const users = pgTable("users", {
  id: serial("id").primaryKey(), username: varchar("username", { length: 40 }).notNull(), email: varchar("email", { length: 255 }).notNull(), passwordHash: varchar("password_hash", { length: 255 }).notNull(), firstName: varchar("first_name", { length: 80 }).notNull(), lastName: varchar("last_name", { length: 80 }).notNull(), avatar: text("avatar"), bio: text("bio"), role: roleEnum("role").default("user").notNull(), suspended: boolean("suspended").default(false).notNull(), xp: integer("xp").default(0).notNull(), totalScore: integer("total_score").default(0).notNull(), gamesPlayed: integer("games_played").default(0).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({ emailIdx: uniqueIndex("users_email_idx").on(table.email), usernameIdx: uniqueIndex("users_username_idx").on(table.username) }));
export const profiles = pgTable("profiles", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), favoriteGames: text("favorite_games").array(), playtimeMinutes: integer("playtime_minutes").default(0).notNull(), level: integer("level").default(1).notNull(), joinedAt: timestamp("joined_at", { withTimezone: true }).defaultNow().notNull() }, (table) => ({ userIdx: uniqueIndex("profiles_user_idx").on(table.userId) }));
export const posts = pgTable("posts", { id: serial("id").primaryKey(), authorId: integer("author_id").notNull().references(() => users.id, { onDelete: "cascade" }), body: text("body").notNull(), likesCount: integer("likes_count").default(0).notNull(), commentsCount: integer("comments_count").default(0).notNull(), sharesCount: integer("shares_count").default(0).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const likes = pgTable("likes", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), postId: integer("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => ({ uniqueLike: uniqueIndex("likes_user_post_idx").on(table.userId, table.postId) }));
export const comments = pgTable("comments", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), postId: integer("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }), body: text("body").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const games = pgTable("games", { id: serial("id").primaryKey(), slug: varchar("slug", { length: 80 }).notNull(), name: varchar("name", { length: 120 }).notNull(), genre: varchar("genre", { length: 80 }).notNull(), active: boolean("active").default(true).notNull() }, (table) => ({ slugIdx: uniqueIndex("games_slug_idx").on(table.slug) }));
export const gameScores = pgTable("game_scores", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), gameId: integer("game_id").notNull().references(() => games.id, { onDelete: "cascade" }), score: integer("score").notNull(), level: integer("level").default(1).notNull(), playedAt: timestamp("played_at", { withTimezone: true }).defaultNow().notNull() });
export const computers = pgTable("computers", { id: serial("id").primaryKey(), label: varchar("label", { length: 30 }).notNull(), status: computerStatusEnum("status").default("available").notNull(), hourlyRateCents: integer("hourly_rate_cents").default(300).notNull(), totalMinutes: integer("total_minutes").default(0).notNull() }, (table) => ({ labelIdx: uniqueIndex("computers_label_idx").on(table.label) }));
export const reservations = pgTable("reservations", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), computerId: integer("computer_id").notNull().references(() => computers.id, { onDelete: "restrict" }), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), status: reservationStatusEnum("status").default("confirmed").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const sessions = pgTable("sessions", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 128 }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => ({ tokenIdx: uniqueIndex("sessions_token_idx").on(table.tokenHash) }));
export const usersRelations = relations(users, ({ many, one }) => ({ posts: many(posts), profile: one(profiles), sessions: many(sessions) }));
export const postsRelations = relations(posts, ({ one, many }) => ({ author: one(users, { fields: [posts.authorId], references: [users.id] }), likes: many(likes), comments: many(comments) }));
